defaults: &defaults
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8

development:
  adapter: sqlite3
  database: db/development.sqlite3
  <<: *defaults

test:
  adapter: sqlite3
  database: db/test.sqlite3
  <<: *defaults

production:
  adapter: postgresql
  <<: *defaults